# This is a sample configuration file for the database connection
[database]
host = "localhost"
port = 3306
name = "users"
user = "user"
password = "password"

[test_database]
host = "localhost"
port = 3306
name = "tests"
user = "testuser"
password = "testpassword"

[users]
reserved_usernames = [
    "superuser",
    "admin_user",
    "admin_note",
    "admin_friend",
    "admin",
    "root",
    "superuser",
    "administrator",
    "null",
    "system",
    "user",
    "username",
    "password",
    "login",
    "logout",
    "signup",
    "signin",
    "signout",
    "register",
    "unregister",
    "delete",
    "remove",
    "edit",
    "update",
    "change",
    "profile",
    "account",
    "settings",
    "config",
    "configuration",
    "preferences",
    "preference",
    "home",
    "dashboard",
]
elevated_usernames = ["superuser", "admin_user", "admin_note", "admin_friend"]
