[users]
reserved_usernames = [
    "superuser",
    "admin_user",
    "admin_note",
    "admin_friend",
    "admin",
    "root",
    "superuser",
    "administrator",
    "null",
    "system",
    "user",
    "username",
    "password",
    "login",
    "logout",
    "signup",
    "signin",
    "signout",
    "register",
    "unregister",
    "delete",
    "remove",
    "update",
    "update",
    "change",
    "profile",
    "account",
    "settings",
    "config",
    "configuration",
    "preferences",
    "preference",
    "home",
    "dashboard",
]
